## joint_names
joint_names: [joint1, joint2, joint3, joint4, joint5, joint6]

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
     - joint6
  constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.05
      joint1: {trajectory: 0.1, goal: 0.1}
      joint2: {trajectory: 0.1, goal: 0.1}
      joint3: {trajectory: 0.1, goal: 0.1}
      joint4: {trajectory: 0.1, goal: 0.1}
      joint5: {trajectory: 0.1, goal: 0.1}
      joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
     - joint6

joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1
joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: joint2
joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: joint3
joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: joint4
joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: joint5
joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: joint6

## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
     - joint6

joint1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint1
joint2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint2
joint3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint3
joint4_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint4
joint5_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint5
joint6_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint6

## no further controllers available
