## Nonlinear Model Predicitive Control Parameters
chain_base_link: arm_podest_link
chain_tip_link: arm_7_link
root_frame: world

## joint_names
joint_names: [arm1_joint, arm2_joint, arm3_joint, arm4_joint, arm5_joint, arm6_joint, arm7_joint]

nmpc:
  state_dim: 10
  control_dim: 10
  time_horizon: 0.5
  shooting_nodes: 5
  
  base:
    base_active: false

  constraints:
    state:
      path_constraints:
        min: [-4, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [ 4,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
      terminal_constraints:
        min: [-4, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [ 4,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
    input:
      input_constraints:
        min: [-1, -1, -1, -1, -1, -1, -1]
        max: [ 1,  1,  1,  1,  1,  1,  1]
    min_distance: 0.15
