joint_names: ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']
#action_name: /arm_controller/follow_joint_trajectory
action_name: /arm/joint_trajectory_controller/follow_joint_trajectory
#service_ns: /arm_controller
service_ns: /arm
default_vel: 0.6

# back side positions
home: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
upright: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

