controller_list:
  - name: fake_arm_controller
    joints:
      - arm_shoulder_1_joint
      - arm_shoulder_2_joint
      - arm_shoulder_3_joint
      - arm_wrist_1_joint
      - arm_wrist_2_joint
      - arm_wrist_3_joint
      
  - name: fake_torso_controller
    joints:
      - torso_pan_joint
      - torso_tilt_joint
